# Numpy - Numerical python


- It is a python library used to compute and process single or multi dimensional arrays
- It is written in C
- An Array should be a homegeneous data

In [ ]:
code --> converted --> kernel --> converted --> output

code  --> kernel --> output

In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np

In [ ]:
Maths --> Matrix
program --> Arrays
Deep learning --> Tensor

# Creating an array

## array function

In [26]:
lst = [34,45,56,67]


print(lst , type(lst))


arr = np.array(lst)


print(arr)

[34, 45, 56, 67] <class 'list'>
[34 45 56 67]


In [30]:
lst = (34,45,56,67)


print(lst , type(lst))


arr = np.array(lst)


print(arr , type(arr))

(34, 45, 56, 67) <class 'tuple'>
[34 45 56 67] <class 'numpy.ndarray'>


In [33]:
lst = [[1,2,3] , [4,5,6] , [4,5,6] , [4,5,6] ,[4,5,6]]

arr = np.array(lst)


print(arr)

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [34]:
lst = [[[1,2,3] , [4,5,6]] ,[[11,12,13] , [14,15,16]]]

arr = np.array(lst)


print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [35]:
lst = [[[1,2,3] , [4,5,6]] ,[[11,12,13] , [14,15,16]] ,[[11,12,13] , [14,15,16]] ,[[11,12,13] , [14,15,16]]]

arr = np.array(lst)


print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]]


In [38]:
# Few important attributes 

lst = [[1,2,3] , [4,5,6] ]

arr = np.array(lst)


print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
# size --> Totalelements in the array

print(arr.size)


# Shape ---> The shape of the array

print(arr.shape)

# ndim --> dimension of the array

print(arr.ndim)

6
(2, 3)
2


In [42]:
lst = [[[1,2,3] , [4,5,6]] , [[1,2,3] , [4,5,6]]]

arr = np.array(lst)


print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
# size --> Total elements in the array

print(arr.size)


# Shape ---> The shape of the array (depth , rows, columns)

print(arr.shape)

# ndim --> dimension of the array

print(arr.ndim)

12
(2, 2, 3)
3


# 2. Creating an array using an arange function

In [47]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
list(range(5,10))

[5, 6, 7, 8, 9]

In [50]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [51]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
list(range(5.5,10.5))

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
np.arange(5.5,10.5)

array([5.5, 6.5, 7.5, 8.5, 9.5])

In [57]:
np.arange('2024-01-01' , '2024-01-10' , dtype ='datetime64') 

array(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
       '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
       '2024-01-09'], dtype='datetime64[D]')

In [59]:
# monday for jan

np.arange('2024-01-01', '2024-01-31', 7, dtype='datetime64')

array(['2024-01-01', '2024-01-08', '2024-01-15', '2024-01-22',
       '2024-01-29'], dtype='datetime64[D]')

In [58]:
print(np.arange('2024-01-01' , '2024-01-10' , dtype ='datetime64') )

['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09']


In [64]:
print(np.arange('2024-01-01' , '2024-01-11' , dtype ='datetime64') )

['2024-01-01' '2024-01-02' '2024-01-03' '2024-01-04' '2024-01-05'
 '2024-01-06' '2024-01-07' '2024-01-08' '2024-01-09' '2024-01-10']


In [68]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
np.linspace(0,10,11 )

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [70]:
np.linspace(0,10,11 , dtype = int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# Zeros , zero's like

In [74]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.zeros((2,3) , dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [76]:
np.zeros((6,) , dtype = int)

array([0, 0, 0, 0, 0, 0])

In [77]:
np.zeros((6,4) , dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [93]:
lst = [[[1,2,3] , [4,5,6]] ,[[11,12,13] , [14,15,16]]]

arr = np.array(lst)


print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [85]:
np.zeros_like(arr)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [86]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

# ones , ones like

In [83]:
np.ones((2,3) , dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [98]:
lst = [[[1,2,3] , [4,5,6]] ,[[11,12,13] , [14,15,16]]]

arr = np.array(lst)


print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [99]:
np.ones_like(arr)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# Identity matrix

- square matrix
- dia are 1 and rest all are 0

In [100]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
np.identity(4 , dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [103]:
np.eye(4,5 , dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

# Creating an array using an random function

In [109]:
np.random.rand(4,5) # 0-1

array([[0.94400751, 0.09361617, 0.71587494, 0.60040046, 0.40129778],
       [0.76545439, 0.44076357, 0.26541864, 0.20336861, 0.4251168 ],
       [0.81158926, 0.18713741, 0.14002878, 0.55694648, 0.25328902],
       [0.63095022, 0.63442852, 0.37586964, 0.14850316, 0.02127523]])

In [110]:
np.random.randn(4,5)

array([[ 0.8342393 ,  1.60229817, -0.18947151,  0.47418794, -0.55169847],
       [ 0.53323998,  0.39071391,  1.21788214,  2.22186063, -0.76574648],
       [ 0.61211711,  1.05797327, -0.89357913, -0.72778581, -2.87430689],
       [ 1.58707033,  0.73414452, -0.39245607, -1.32017516, -0.73553505]])

In [129]:
np.random.randint(10,20)

18

In [142]:
np.random.randint(1,7)

4

In [145]:
np.random.randint(10,20 , size = (3,4))

array([[11, 12, 17, 12],
       [10, 17, 12, 12],
       [10, 17, 17, 10]])

In [159]:
np.random.rand(4,5)

array([[0.14790391, 0.51579028, 0.39425832, 0.06988013, 0.33822577],
       [0.01103722, 0.76752786, 0.87472213, 0.53359432, 0.08441275],
       [0.8243312 , 0.5045812 , 0.88161863, 0.17404628, 0.40295789],
       [0.83212654, 0.97866247, 0.61916477, 0.86992066, 0.2488769 ]])

In [160]:
np.random.rand(4,5)

array([[0.64303396, 0.30045066, 0.24536055, 0.54602368, 0.11976084],
       [0.34309671, 0.63178697, 0.83155192, 0.35538789, 0.23541176],
       [0.80203533, 0.60371286, 0.49363014, 0.93305116, 0.65311175],
       [0.67884942, 0.31165887, 0.12014239, 0.15491823, 0.76611197]])

In [161]:
np.random.seed(34)

np.random.rand(4,5)

array([[0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085],
       [0.93615854, 0.42657438, 0.25308645, 0.18996531, 0.41482463],
       [0.01342061, 0.64847278, 0.86936875, 0.6090357 , 0.80799282],
       [0.82651133, 0.27168333, 0.83647644, 0.28254136, 0.1383086 ]])

In [162]:
np.random.seed(34)

np.random.rand(4,5)

array([[0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085],
       [0.93615854, 0.42657438, 0.25308645, 0.18996531, 0.41482463],
       [0.01342061, 0.64847278, 0.86936875, 0.6090357 , 0.80799282],
       [0.82651133, 0.27168333, 0.83647644, 0.28254136, 0.1383086 ]])

In [158]:
np.random.seed(35)

np.random.rand(4,5)

array([[0.45805495, 0.30834961, 0.23148705, 0.27742455, 0.81723481],
       [0.11134664, 0.62643723, 0.27678789, 0.68217467, 0.67897078],
       [0.79671742, 0.04580216, 0.91259827, 0.21381599, 0.3036373 ],
       [0.98906362, 0.1858815 , 0.98872484, 0.75008423, 0.22238605]])

# Reshape