In [1]:
import numpy as np

In [5]:
arr = np.random.randint(10,50, size = (6,6))

arr

array([[42, 17, 28, 47, 35, 21],
       [21, 43, 37, 18, 44, 16],
       [45, 31, 17, 42, 36, 13],
       [17, 18, 14, 36, 26, 22],
       [12, 32, 10, 37, 13, 25],
       [36, 41, 23, 47, 36, 38]])

In [6]:
arr

array([[42, 17, 28, 47, 35, 21],
       [21, 43, 37, 18, 44, 16],
       [45, 31, 17, 42, 36, 13],
       [17, 18, 14, 36, 26, 22],
       [12, 32, 10, 37, 13, 25],
       [36, 41, 23, 47, 36, 38]])

# Reshape

In [7]:
arr.size

36

In [9]:
arr.reshape(3 ,12)

array([[42, 17, 28, 47, 35, 21, 21, 43, 37, 18, 44, 16],
       [45, 31, 17, 42, 36, 13, 17, 18, 14, 36, 26, 22],
       [12, 32, 10, 37, 13, 25, 36, 41, 23, 47, 36, 38]])

In [10]:
arr = np.arange(12)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [16]:
arr.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# Infer

In [20]:
a = ['Sriram@gmail.com' , 'Abhijeet@yahoo.com' , 'Abhishek@gmail.com', 'Chandan@hotmail.com',
       'xyz@gmail.com' , 'akanksha@gmail.com']


arr = np.array(a)

arr

array(['Sriram@gmail.com', 'Abhijeet@yahoo.com', 'Abhishek@gmail.com',
       'Chandan@hotmail.com', 'xyz@gmail.com', 'akanksha@gmail.com'],
      dtype='<U19')

In [ ]:
<U19 --> An unistring where the length of all the strings is less than 19

In [21]:
arr.size

6

In [ ]:
# row 2
# column --> system to decide

In [22]:
arr.reshape(2,-1)

array([['Sriram@gmail.com', 'Abhijeet@yahoo.com', 'Abhishek@gmail.com'],
       ['Chandan@hotmail.com', 'xyz@gmail.com', 'akanksha@gmail.com']],
      dtype='<U19')

In [24]:
arr.reshape(-1,1,2)

array([[['Sriram@gmail.com', 'Abhijeet@yahoo.com']],

       [['Abhishek@gmail.com', 'Chandan@hotmail.com']],

       [['xyz@gmail.com', 'akanksha@gmail.com']]], dtype='<U19')

In [25]:
arr.reshape(-1,-1,2)

ValueError: can only specify one unknown dimension

In [28]:
np.arange(100).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [29]:
np.arange(120).reshape(6,-1)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119]])

In [30]:
np.arange(125).reshape(6,-1)

ValueError: cannot reshape array of size 125 into shape (6,newaxis)

In [ ]:
size = depth * rows * column

# Transpose

In [38]:
arr = np.random.randint(10,50, size = (2,4))

arr

array([[36, 33, 20, 31],
       [48, 19, 16, 13]])

In [34]:
arr.T

array([[24, 26],
       [22, 18],
       [14, 39],
       [36, 26]])

In [36]:
arr = np.identity(5 , dtype = int)

arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
arr.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Flatten , Ravel

In [42]:
arr = np.random.randint(10,50, size = (2,4))

arr

array([[33, 35, 48, 40],
       [13, 13, 12, 43]])

In [50]:
print(arr.flatten.__doc__)

a.flatten(order='C')

    Return a copy of the array collapsed into one dimension.

    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.

    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.

    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.

    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4])


In [43]:
arr.flatten()

array([33, 35, 48, 40, 13, 13, 12, 43])

In [44]:
arr.ravel()

array([33, 35, 48, 40, 13, 13, 12, 43])

In [45]:
arr = np.random.randint(10,50, size = (4,5))

arr

array([[24, 25, 48, 10, 46],
       [36, 14, 12, 43, 30],
       [33, 30, 27, 45, 35],
       [22, 13, 22, 47, 12]])

In [53]:
arr.flatten(order = 'F')

array([24, 36, 33, 22, 25, 14, 30, 13, 48, 12, 27, 22, 10, 43, 45, 47, 46,
       30, 35, 12])

In [52]:
arr.flatten()

array([24, 25, 48, 10, 46, 36, 14, 12, 43, 30, 33, 30, 27, 45, 35, 22, 13,
       22, 47, 12])

In [46]:
for i in arr:
    print(i)

[24 25 48 10 46]
[36 14 12 43 30]
[33 30 27 45 35]
[22 13 22 47 12]


In [47]:
for i in arr.ravel():
    print(i)

24
25
48
10
46
36
14
12
43
30
33
30
27
45
35
22
13
22
47
12


In [48]:
for i in arr.flatten():
    print(i)

24
25
48
10
46
36
14
12
43
30
33
30
27
45
35
22
13
22
47
12


# Arithmetic operations element wise

In [59]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]


c = []

for i in range(len(a)):
    c.append(a[i] + b[i])
    
c

[7, 9, 11, 13, 15]

In [60]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


a+b

array([ 7,  9, 11, 13, 15])

In [63]:
a-b

array([-5, -5, -5, -5, -5])

In [64]:
a*b

array([ 6, 14, 24, 36, 50])

In [65]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [66]:
a**b

array([      1,     128,    6561,  262144, 9765625])

In [67]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10,11])


a+b

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [80]:
a = np.arange(24).reshape(4,-1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [81]:
b = np.arange(24).reshape(4,-1)**2
b

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [72]:
a * b

array([[    0,     1,     8,    27,    64,   125],
       [  216,   343,   512,   729,  1000,  1331],
       [ 1728,  2197,  2744,  3375,  4096,  4913],
       [ 5832,  6859,  8000,  9261, 10648, 12167]])

# Matrix multiplication

In [75]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
2 X 3 : 3 X 2

In [79]:
a.dot(b)

array([[10, 13],
       [28, 40]])

In [ ]:
0+2+8       0+3+10
0+8+20      3+12+25

In [ ]:
10     13
28     40

In [82]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [83]:
b

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289],
       [324, 361, 400, 441, 484, 529]])

In [84]:
a.dot(b) # 4 X 6 : 4 :6

ValueError: shapes (4,6) and (4,6) not aligned: 6 (dim 1) != 4 (dim 0)

In [85]:
a.dot(b.T) # 4 X 6 : 6 X 4

array([[  225,  1425,  3705,  7065],
       [  555,  4131, 11379, 22299],
       [  885,  6837, 19053, 37533],
       [ 1215,  9543, 26727, 52767]])

# Universal functions

In [86]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


a+b

array([ 7,  9, 11, 13, 15])

In [87]:
np.add(a , b)

array([ 7,  9, 11, 13, 15])

In [88]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([10,20,30,40,50])

a+b+c

array([17, 29, 41, 53, 65])

In [89]:
np.add(a , b , c)

array([ 7,  9, 11, 13, 15])

In [90]:
c

array([ 7,  9, 11, 13, 15])

In [91]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.zeros_like(a)



In [92]:
c

array([0, 0, 0, 0, 0])

In [93]:
np.add(a , b , c)

array([ 7,  9, 11, 13, 15])

In [94]:
c

array([ 7,  9, 11, 13, 15])

# Unary function --> Any function that returns 1 value as an output


- sum
- min
- max


In [95]:
np.random.seed(20)

age = np.random.randint(20 , 60 , size = (10,))

age

array([55, 46, 35, 51, 48, 46, 29, 40, 31, 42])

In [96]:
age.sum()

423

In [97]:
np.sum(age)

423

In [98]:
age.min()

29

In [99]:
age.max()

55

In [100]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [101]:
a.sum()

15

### Axis 

In [102]:
a.sum(axis = 0) # axis = 0 --> columns

array([3, 5, 7])

In [104]:
a.sum(axis = 1) # axis = 1 --> rows

array([ 3, 12])

# Statistical functions 


- mean
- mode
- median
- std 
- var

In [106]:
np.random.seed(20)

age = np.random.randint(20 , 60 , size = (10,))

age

array([55, 46, 35, 51, 48, 46, 29, 40, 31, 42])

In [108]:
np.mean(age)

42.3

In [107]:
l =[55, 46, 35, 51, 48, 46, 29, 40, 31, 42]


sum(l) / len(l)

42.3

In [110]:
# Len--> odd 

l = [55, 46, 35, 51, 48, 46, 29, 40, 31, 42,32]

l.sort()

l

[29, 31, 32, 35, 40, 42, 46, 46, 48, 51, 55]

In [111]:
# Len--> even 

l = [55, 46, 35, 51, 48, 46, 29, 40, 31, 42]

l.sort()

l

[29, 31, 35, 40, 42, 46, 46, 48, 51, 55]

In [112]:
(42 +46) / 2

44.0

In [116]:
np.mean(age)

42.3

In [113]:
np.median(age)

44.0

In [114]:
np.std(age)

8.124653838779842

In [115]:
np.var(age)

66.01000000000002

# Indexing and slicing

# 1D

In [117]:
age

array([55, 46, 35, 51, 48, 46, 29, 40, 31, 42])

In [118]:
age[2]

35

In [119]:
age[-4]

29

In [120]:
age[2:6]

array([35, 51, 48, 46])

# 2 D

In [121]:
a = np.arange(36).reshape(6,6)**2

a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [123]:
a[1][2]

64

In [ ]:
array[depth , rows , columns]

In [124]:
a[1 , 2]

64

In [125]:
a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [126]:
# 169,  196,  225


a[2 , 1:4]

array([169, 196, 225])

In [128]:
a[2:4 , 2:4]

array([[196, 225],
       [400, 441]])

In [129]:
a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [130]:
a[1:5 , 1::2]

array([[ 49,  81, 121],
       [169, 225, 289],
       [361, 441, 529],
       [625, 729, 841]])

In [131]:
a[2:5:2 , 2:4]

array([[196, 225],
       [676, 729]])

In [132]:
a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [133]:
a[[1,3,4] , 1:5]

array([[ 49,  64,  81, 100],
       [361, 400, 441, 484],
       [625, 676, 729, 784]])

In [134]:
a

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [135]:
a[1:5,[1,3,4]]

array([[ 49,  81, 100],
       [169, 225, 256],
       [361, 441, 484],
       [625, 729, 784]])